---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: clone-submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update

- name: install
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - wget -qO hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.63.1/hugo_extended_0.63.1_Linux-64bit.deb
  - dpkg -i hugo.deb
  - npx pnpm i
  - (cd /drone/src/themes/scarecrow/ && npx pnpm i --only prod)
  - cp /drone/src/themes/scarecrow/node_modules/fuse.js/dist/fuse.js /drone/src/themes/scarecrow/assets/scripts/fuse.min.js

- name: build
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - hugo

- name: deploy
  image: cschlosser/drone-ftps
  settings:
    secure: true
    clean_dir: true
    host: sftp://strootje.com.transurl.nl
    secrets: [ SFTP_USER, SFTP_PASS ]
    src_dir: /drone/src/public
    dest_dir: /www
  environment:
    SFTP_USER:
      from_secret: SFTP_USER
    SFTP_PASS:
      from_secret: SFTP_PASS


# - name: publish
#   image: plugins/gh-pages
#   settings:
#     username: octocat
#     password: p455w0rd
#     pages_directory: public/
#     upstream_name: upstream

volumes:
- name: hugo-bin
  temp: {}
