---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: clone-submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update

- name: install
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - wget -qO hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.63.1/hugo_extended_0.63.1_Linux-64bit.deb
  - dpkg -i hugo.deb
  - npx pnpm i
  - (cd /drone/src/themes/scarecrow/ && npx pnpm i --only prod)
  - cp /drone/src/themes/scarecrow/node_modules/fuse.js/dist/fuse.js /drone/src/themes/scarecrow/assets/scripts/fuse.min.js

- name: build
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - npx pnpm run build

- name: deploy
  image: node
  when:
    branch:
    - master
  commands:
  - apt update && apt install lftp
  - lftp -e "set sftp:auto-confirm yes; mirror -eR ./public /www" -u $FTP_USERNAME,$FTP_PASSWORD $PLUGIN_HOSTNAME
  environment:
    PLUGIN_HOSTNAME:
      from_secret: SFTP_HOST
    FTP_USERNAME:
      from_secret: SFTP_USER
    FTP_PASSWORD:
      from_secret: SFTP_PASS

volumes:
- name: hugo-bin
  temp: {}
