---
kind: pipeline
name: default

trigger:
  branch:
  - master

steps:
- name: clone-submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update

- name: install
  image: node
  volumes:
  - name: hugo-bin
    path: /usr/local/bin
  commands:
  - wget -qO hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.63.1/hugo_extended_0.63.1_Linux-64bit.deb
  - dpkg -i hugo.deb
  - npx pnpm i
  - (cd /drone/src/themes/scarecrow/ && npx pnpm i --only prod)
  - cp /drone/src/themes/scarecrow/node_modules/fuse.js/dist/fuse.js /drone/src/themes/scarecrow/assets/scripts/fuse.min.js

  #- name: build
  #  image: node
  #  volumes:
  #  - name: hugo-bin
  #    path: /usr/local/bin
  #  commands:
  #  - hugo
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.63.1
    extended: true
    validate: true
    url: https://strootje.com

# - name: publish
#   image: plugins/gh-pages
#   settings:
#     username: octocat
#     password: p455w0rd
#     pages_directory: public/
#     upstream_name: upstream

volumes:
- name: hugo-bin
  temp: {}
